sudo: required
language: php
dist: trusty

php:
  - 7.1

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - php artisan key:generate
  - vendor/bin/phpunit
  - php artisan dusk
